spring.application.name=Ifeel
spring.datasource.url=jdbc:postgresql://localhost:5432/ifeel
spring.datasource.username=cb97
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update